=== MrWalkan/xml-cssDesigned/catalog_19030867.dtd
<!-- The NOTATION Declaration corresponds to the URI referenced from the NDATA datatype argument which is further specified to what kind of data actually it is in system -->
<!NOTATION JPGfile SYSTEM "image/jpeg">
<!NOTATION PNGfile SYSTEM "image/png">

<!-- The given ENTITY declartion defines an Entity to be parsed externally for representing a non-XML file -->
<!-- The NDATA or Notation Data represents an Entity to be of certain data of type determined by the dataType argument which corresponds to a Notation -->
<!ENTITY img0 SYSTEM "catalog_19030867.xml">
<!ENTITY img01 SYSTEM "images/tucaStoreLogo.png" NDATA PNGfile>
<!ENTITY img1 SYSTEM "images/sketchesOfDajeeling.jpg" NDATA JPGfile>
<!ENTITY img2 SYSTEM "images/word.jpg" NDATA JPGfile>
<!ENTITY img3 SYSTEM "images/agora.jpg" NDATA JPGfile>
<!ENTITY img4 SYSTEM "images/dobleVida.jpg" NDATA JPGfile>
<!ENTITY img5 SYSTEM "images/billieHoliday.jpg" NDATA JPGfile>
<!ENTITY img6 SYSTEM "images/justice.jpg" NDATA JPGfile>
<!ENTITY img7 SYSTEM "images/everMore.jpg" NDATA JPGfile>
<!ENTITY img8 SYSTEM "images/loveSongsForRobots.jpg" NDATA JPGfile>
<!ENTITY img9 SYSTEM "images/theBlueRoom.jpg" NDATA JPGfile>
<!ENTITY img10 SYSTEM "images/red.jpg" NDATA JPGfile>
<!ENTITY img11 SYSTEM "images/lemonTree.jpg" NDATA JPGfile>
<!ENTITY img12 SYSTEM "images/theGodfather.jpg" NDATA JPGfile>
<!ENTITY img13 SYSTEM "images/vivaLaVida.png" NDATA PNGfile>
<!ENTITY img14 SYSTEM "images/santaClaus.jpg" NDATA JPGfile>
<!ENTITY img15 SYSTEM "images/iLovedYou.jpg" NDATA JPGfile>

<!-- Child Elements of An Element can be declared inside the parentheses separated by comma  -->
<!ELEMENT tuca_Root (tuca_Store,tuca_AudioInventory,tuca_Copyright)>
<!-- ATTLIST Declartion is used to Define the Attribute specification of an Element -->
<!-- Below ATTLIST defines the namespace named xmlns attached to the root element tuca_Root whose value representing the quoted URI is of Character Data and is fixed -->
<!ATTLIST tuca_Root xmlns CDATA #FIXED "http//www.w3schools.com">
    <!ELEMENT tuca_Store (tuca_StoreLogo,tuca_StoreName,tuca_Owner,tuca_Address,tuca_WebsiteAddress,tuca_ContactDetails,tuca_StoreDescription)>
    <!ATTLIST tuca_Store source ENTITY #REQUIRED>
        <!-- The ELEMENT Declartion with #PCDATA inside parentheses defines any text content inside that Element is parsed by the Parser or processed by the XML Processor -->
        <!ELEMENT tuca_StoreLogo (#PCDATA)>
        <!ELEMENT tuca_StoreName (#PCDATA)>
        <!ELEMENT tuca_Owner (#PCDATA)>
        <!ELEMENT tuca_Address (#PCDATA)>
        <!ELEMENT tuca_WebsiteAddress (#PCDATA)>
        <!-- The + sign after the Element name represents that the Element can occur one or more times -->
        <!ELEMENT tuca_ContactDetails (tuca_TelephoneNumber+,tuca_Email)>
            <!ELEMENT tuca_TelephoneNumber (#PCDATA)>
            <!ELEMENT tuca_Email (#PCDATA)>
        <!ELEMENT tuca_StoreDescription (#PCDATA)>
        <!-- The ENTITY Attribute type represents a non-XML file in below context which is defined by Notation -->
        <!-- the attribute-value #REQUIRED represents that the givena attribtue must be defined during an Element definition -->
        <!ATTLIST tuca_StoreLogo source ENTITY #REQUIRED>
        <!-- The attribute-type Enumerated list contains data inside parentheses spearated by | from which any one of them needs to be defined in the attribute value -->
        <!-- The attribute-value is set to "Male" as default which means, if the given attribute is not defined, the XML parser reads the attribute value as give default value  -->
        <!ATTLIST tuca_Owner sex (Male|Female|Other) "Male">
        <!-- The NMTOKEN represents a vaild XML name -->
        <!ATTLIST tuca_Address country NMTOKEN #REQUIRED>
    <!-- The * sign after an Element name represents that the Element can occur 0 or more times -->
    <!ELEMENT tuca_AudioInventory (tuca_Album*)>
    <!-- The ? sign represents that the Element may occur once or may not occur -->
    <!ELEMENT tuca_Album (tuca_AlbumType,tuca_Cover,tuca_Title,tuca_Genre+,tuca_Band?,tuca_Director*,tuca_Producer+,tuca_Composer*,tuca_Writer+,tuca_Artist+,tuca_Studio+,tuca_RecordCompany,tuca_ReleaseDate,tuca_Description,tuca_AudioQuality,tuca_Songs,tuca_Price)>
    <!ATTLIST tuca_Album language CDATA #IMPLIED albumID ID #REQUIRED available (true|false) "false">
        <!ELEMENT tuca_AlbumType (#PCDATA)>
        <!-- the EMPTY element-content declares an Empty element without text content -->
        <!ELEMENT tuca_Cover EMPTY>
        <!ELEMENT tuca_Title (#PCDATA)>
        <!ELEMENT tuca_Genre (#PCDATA)>
        <!ELEMENT tuca_Band (tuca_Member+)>
            <!ELEMENT tuca_Member (#PCDATA)>
        <!ELEMENT tuca_Director (#PCDATA)>
        <!ELEMENT tuca_Producer (#PCDATA)>
        <!ELEMENT tuca_Composer (#PCDATA)>        
        <!ELEMENT tuca_Writer (#PCDATA)>
        <!ELEMENT tuca_Artist (#PCDATA)>
        <!ELEMENT tuca_Studio (#PCDATA)>
        <!ELEMENT tuca_RecordCompany (#PCDATA)>
        <!ELEMENT tuca_ReleaseDate (#PCDATA)>
        <!ELEMENT tuca_Description (#PCDATA)>
        <!ELEMENT tuca_AudioQuality (tuca_SampleRate,tuca_BitDepth,tuca_Channel)>
            <!ELEMENT tuca_SampleRate (#PCDATA)>
            <!ELEMENT tuca_BitDepth (#PCDATA)>
            <!ELEMENT tuca_Channel (#PCDATA)>
        <!ELEMENT tuca_Songs (tuca_Size,tuca_Song+)>
            <!ELEMENT tuca_Size (#PCDATA)>
            <!ELEMENT tuca_Song (tuca_SongTitle,tuca_Duration,tuca_SongSize)>
                <!ELEMENT tuca_SongTitle (#PCDATA)>
                <!ELEMENT tuca_Duration (#PCDATA)>
                <!ELEMENT tuca_SongSize (#PCDATA)>
        <!ELEMENT tuca_Price (#PCDATA)>
        <!ATTLIST tuca_Cover source ENTITY #REQUIRED>
        <!-- Any number of Attributes can be defined inside the ATTLIST declaration -->
        <!-- the attribute-type ID represents a unique value in the XML instance -->
        <!ATTLIST tuca_Band origin NMTOKEN #REQUIRED bandID ID #REQUIRED>
        <!-- The attribute-value IDREF represents a value referenced from available ID in XML instance -->
        <!-- the attribute-value #IMPLIED defines that the Attribute may or May not be defined while Element Declartion in XML document/instance/file -->
        <!ATTLIST tuca_Artist role (Main|Feature|With) "Main" refBandID IDREF #IMPLIED>
        <!ATTLIST tuca_AudioQuality bitrate CDATA #REQUIRED>
        <!ATTLIST tuca_Songs duration CDATA #REQUIRED>
        <!ATTLIST tuca_Size format NMTOKEN #REQUIRED>
        <!ATTLIST tuca_Song track CDATA #REQUIRED>
        
    <!ELEMENT tuca_Copyright (#PCDATA)>

=== MrWalkan/xml-cssDesigned/catalog_19030867.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Prolog Declaration  -->

<!-- <!DOCTYPE tuca_Root SYSTEM "catalog_19030867.dtd"> -->

<!-- Stylesheet Declartion is an XML processing instruction and is a part of XML prolog which is used to link CSS in below context -->
<?xml-stylesheet type="text/css" href="catalog_19030867.css"?>
<!-- root Element -->
<!-- for DTD  -->
<!-- <tuca_Root xmlns="http//www.w3schools.com"> -->
<tuca_Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="catalog_19030867.xsd"
>
	<!-- tuca_Store is an Element, moreover division containing important details about the Store -->
	<!-- It is also references an background image in CSS -->
	<tuca_Store source="img0">
		<!-- It references a logo image for the Store -->
		<tuca_StoreLogo source="img01" />
		<!-- It represents the name/title of the store -->
		<tuca_StoreName>Tune Casket</tuca_StoreName>
		<!-- It represents the name of the Owner of the Store with the sex info -->
		<tuca_Owner sex="Female">Ramani Shrestha</tuca_Owner>
		<!-- It represents the location of the Store -->
		<tuca_Address country="NP">Bigc Complex, Naxal, Kathmandu</tuca_Address>
		<!-- It represents the website address URL of the Store -->
		<tuca_WebsiteAddress>www.tunecasket.com.np</tuca_WebsiteAddress>
		<!-- It represents the contact details to communicate with the store over distance -->
		<tuca_ContactDetails>
			<!-- It represents the telephone number associated with the store -->
			<!-- A Store can have multiple telephone numbers -->
			<tuca_TelephoneNumber>01-7359320</tuca_TelephoneNumber>
			<tuca_TelephoneNumber>01-2482012</tuca_TelephoneNumber>
			<!-- It represents an available email of the store for any inquiry -->
			<tuca_Email>query@tuca.com.np</tuca_Email>
		</tuca_ContactDetails>
		<!-- It represents a detail description about the store -->
		<tuca_StoreDescription>For over 30 years, The Music Store has been in its new site. Formerly known as Tune Casket, the new owners Ramani Shrestha and Bishal Gharti Chhetri, bought the shop in 1993 and renamed it The Music Store. Garber Music began in a 2,000-square-foot space with three teaching studios and a small collection of books, instruments, and accessories. The Music Store has expanded to 5,000 square feet and now has 28 Practice Rooms/Studios with a total of 20 instructors. We have one of Nepal's best sheet music collections, 16 guitar and amplifier lines, band and orchestra instruments, accessories, rentals, and a repair shop, as well as 16 guitar and amplifier lines, band and orchestra instruments, accessories, rentals, and a repair shop. Online shopping, teacher workshops, sheet music research services, and news alerts via e-mail news blasts and event invites (subscribe below), Twitter, Instagram, and Facebook are also available. The Music Store has grown significantly over time. However, we have remained committed to providing excellent education, high-quality goods, and outstanding customer service. If you are a teacher, admin, parent, or student, we consider ourselves to be your music education partner. Come in and join the family at The Music Store. We are excited to be of service to you.Staff members who specialize in guitar, trumpet, percussion, upright bass, and piano performance can be found in our instrument section. Others have finished their educations while others are still in school. All takes part in bands or sacred settings. Each member of our staff has extensive musical expertise and experience, which they put to good use in assisting you in your quest for instruments, sheet music, lessons, rentals, or repairs. With every purchase, we take pride in being able to answer your questions, even if we have to do some homework, provide you with truthful, trustworthy advice, and make you feel like you have the support of family. We anticipate your arrival.</tuca_StoreDescription>
	</tuca_Store>

	<!-- tuca_AudioInventory is an Another division to store Audio Albums details. -->
	<tuca_AudioInventory>
		<!-- It represents an Audio Album and has further details available in its attribute and child-elements -->
		<!-- A Music Store can have 0 or many Audio Albums in their Inventory -->
		<tuca_Album language="Nepali" albumID="AWA01" available="true">
			<!-- It represents the type of Album like EP(Extended play), Studio, Live, Compilation, Single etc. -->
			<tuca_AlbumType>EP</tuca_AlbumType>
			<!-- It represents an Album cover image for the given Audio Album -->
			<tuca_Cover source="img1" />
			<!-- It represents the name/title of the Album -->
			<tuca_Title>Sketches of Darjeeling</tuca_Title>
			<!-- It represents the Genre of the Album -->
			<!-- An Album can have multiple Genre for different musics -->
			<tuca_Genre>Folk</tuca_Genre>
			<!-- It represents the name of the producer(s) who produced the Songs/Musics of the album -->
			<!-- An Album Music/Song can have 0 or many Producer(s) -->
			<tuca_Producer>Bipul Chetri</tuca_Producer>
			<!-- It represents the name of Composer(s) who composed the music of the Song -->
			<!-- An album is composed by 0 or many Composer(s) -->
			<tuca_Composer>Bishal Gharti Chhetri</tuca_Composer>
			<!-- It represents the writer of the Song commonly known as the lyricist -->
			<!-- An Album Song is written by many Writers/Lyricists -->
			<tuca_Writer>Bipul Chetri</tuca_Writer>
			<!-- It represents the artist or singer who performed the song -->
			<!-- An Album can have 0 or more number of Artists -->
			<tuca_Artist role="Main">Bipul Chetri</tuca_Artist>
			<!-- It represents the studio where the music was recorded -->
			<!-- Each Song/Music in the Album could be recorded in one or many recording studios -->
			<tuca_Studio>Plug n' Play Studios</tuca_Studio>
			<!-- IT represents a company who markets/publishes the music/song/album including their copyright enforcement -->
			<tuca_RecordCompany>OKListen Media</tuca_RecordCompany>
			<!-- It represent the date when the album was released -->
			<tuca_ReleaseDate>2014-07-25</tuca_ReleaseDate>
			<!-- It represents a discription detail of the Album -->
			<tuca_Description>In the beginning of 2013, a song exploded like flames around the Internet. It was appropriately named ‘Wildfire/Dadhelo.' The overwhelming positive feedback from listeners, as well as the pace at which this tuca Song was added to everyone's playlist, laid the groundwork for "Sketches of Darjeeling. With his song "Wildfire (Dadelo)," Bipul's voice and musical talents were revealed to the planet. In February 2013, it was captured and posted to SoundCloud. Sketches of Darjeeling, his debut album, was built on this basis. Sketches of Darjeeling, his debut album, was well received. On OKListen.Com, an indie retail music site in India, he was the 'Top Selling Artist' in 2014-15, and he was in the Top Ten in 2015-16.  At the Hero Hits FM 91.2 Awards."</tuca_Description>
			<!-- It represents the technical specificaiton of the Audio or Album Songs -->
			<tuca_AudioQuality bitrate="1411.2 kbps">
				<!-- It represents the number of time the audio was sampled -->
				<tuca_SampleRate>44.1 Khz</tuca_SampleRate>
				<!-- It represents the number of bits of audio information in each sample of Sample Rate -->
				<tuca_BitDepth>16 bit</tuca_BitDepth>
				<!-- It represents the directional audible perspective of the Album's Songs  -->
				<tuca_Channel>Stereo</tuca_Channel>	
			</tuca_AudioQuality>
			<!-- It is parent of collection of child-Element Song and has total time duaration of the album in HH:MM:SS format -->
			<tuca_Songs duration="00:21:05">
				<!-- It represents the size of each Song/Music in MB (MegaByte) and its digital file format-->
				<tuca_Size format="WAV">212.81 MB</tuca_Size>
				<!-- It represents an individual song with its track number in the Album -->
				<tuca_Song track="1/6">
					<!-- It represents the title/name of a Song -->
					<tuca_SongTitle>Mountain High</tuca_SongTitle>
					<!-- It represents the duration of a song olayed untl the end -->
					<tuca_Duration>00:04:00</tuca_Duration>
					<!-- It represents the size of an individual song in MiB (MebiByte) -->
					<tuca_SongSize>40.37 MiB</tuca_SongSize>
				</tuca_Song>
				<tuca_Song track="2/6">
					<tuca_SongTitle>Wildfire (Dadhelo)</tuca_SongTitle>
					<tuca_Duration>00:03:30</tuca_Duration>
					<tuca_SongSize>35.32 MiB</tuca_SongSize>
				</tuca_Song>
				<tuca_Song track="3/6">
					<tuca_SongTitle>Asaar</tuca_SongTitle>
					<tuca_Duration>00:03:49</tuca_Duration>
					<tuca_SongSize>38.52 MiB</tuca_SongSize>
				</tuca_Song>
				<tuca_Song track="4/6">
					<tuca_SongTitle>Deorali Darah</tuca_SongTitle>
					<tuca_Duration>00:03:22</tuca_Duration>
					<tuca_SongSize>33.98 MiB</tuca_SongSize>
				</tuca_Song>
				<tuca_Song track="5/6">
					<tuca_SongTitle>Ram Sailee- Ode to my Father</tuca_SongTitle>
					<tuca_Duration>00:03:20</tuca_Duration>
					<tuca_SongSize>33.64 MiB</tuca_SongSize>
				</tuca_Song>
				<tuca_Song track="6/6">
					<tuca_SongTitle>Rail Garee</tuca_SongTitle>
					<tuca_Duration>00:03:04</tuca_Duration>
					<tuca_SongSize>30.95 MiB</tuca_SongSize>
				</tuca_Song>
			</tuca_Songs>
			<!-- It represents the price of the Album in Nepalese Ruppees -->
			<tuca_Price>3999</tuca_Price>
		</tuca_Album>
		
		<tuca_Album language="Japanese" albumID="AWA02" available="true">
			<tuca_AlbumType>Single</tuca_AlbumType>
			<tuca_Cover source="img2" />
			<tuca_Title>言ノ葉</tuca_Title>
			<tuca_Genre>Pop</tuca_Genre>
			<tuca_Producer>Motohiro Hata</tuca_Producer>
			<tuca_Producer>Tomita Lab.</tuca_Producer>
			<tuca_Producer>皆川真人</tuca_Producer>
			<tuca_Producer>多田彰文</tuca_Producer>
			<tuca_Composer>Senri Oe</tuca_Composer>
			<tuca_Writer>Motohiro Hata</tuca_Writer>
			<tuca_Writer>Senri Oe</tuca_Writer>
